// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset } from '../storyblok.d.ts';
export interface Image {
  asset: StoryblokAsset;
  component: "image";
  _uid: string;
  [k: string]: any;
}

export interface Page {
  body?: (Image | Page | Settings | Text | Video | Work | WorkDetail)[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface Settings {
  group_splash_screen?: any;
  images?: Image[];
  group_tracking?: any;
  enable_tracking?: boolean;
  umami_js_src?: string;
  umami_website_id?: string;
  component: "settings";
  _uid: string;
  [k: string]: any;
}

export interface Text {
  text?: string;
  component: "text";
  _uid: string;
  [k: string]: any;
}

export interface Video {
  asset: StoryblokAsset;
  component: "video";
  _uid: string;
  [k: string]: any;
}

export interface Work {
  marquee?: Text[];
  works: WorkDetail[];
  component: "work";
  _uid: string;
  [k: string]: any;
}

export interface WorkDetail {
  title?: string;
  description?: string;
  assets?: (Image | Video)[];
  component: "work_detail";
  _uid: string;
  [k: string]: any;
}

export type ContentType = Page | Settings | Work;
