// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset } from '../storyblok.d.ts';
export interface Image {
  asset: StoryblokAsset;
  component: "image";
  _uid: string;
  [k: string]: any;
}

export interface Page {
  body?: (Image | Page | Settings | Video | Work | WorkDetail)[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface Settings {
  images?: Image[];
  component: "settings";
  _uid: string;
  [k: string]: any;
}

export interface Video {
  asset: StoryblokAsset;
  component: "video";
  _uid: string;
  [k: string]: any;
}

export interface Work {
  works: WorkDetail[];
  component: "work";
  _uid: string;
  [k: string]: any;
}

export interface WorkDetail {
  title?: string;
  description?: string;
  assets?: (Image | Video)[];
  component: "work_detail";
  _uid: string;
  [k: string]: any;
}

export type ContentType = Page | Settings | Work;
